<?php
//Status
const OK = 0;
const ERROR = 1;
const ERROR_USE_PASS = 2;
const OUT_DATE = -1;
const AUTHEN = 999;

//Delete flag
const DELETED_Y = 1;
const DELETED_N = 0;

//HTTP status
const SUCCESS = 200;
const CLIENT_ERROR = 400;
const AUTHEN_ERROR = 401;
const FORBIDDEN = 403;
const NOT_FOUND = 404;
const SERVER_ERROR = 500;

//Filter OK flag
const IS_ALLOWED = 1;

//Paging
const DEFAULT_PAGE = 1;
const DEFAULT_PAGE_SIZE = 10;
const MAX_DEFAULT_PAGE_SIZE = 100;

//special param value
const NULL_SELECTED = -1;
const IGNORE_OUT_DATE = 1;

// status user
const STATUS_IS_ACTIVE = 1;
const STATUS_INACTIVE = 0;

// status_working user
const STATUS_INTERNSHIP = 1;       // Thực tập
const STATUS_PROBATION = 2;        // Thử việc
const STATUS_OFFICIAL = 3;         // Chính thức

const PASSWORD_ADMIN_SET = 'Admin123';

// day off
const MORNING_START = '08:30:00';
const MORNING_END = '12:00:00';
const AFTERNOON_START = '13:00:00';
const AFTERNOON_END = '17:30:00';

// status day off
const STATUS_DAY_OFF_DAY = 0; // off day
const STATUS_DAY_ON_DAY = 1; // working day

// status work day
const WORK_DAY = 1;
const OFF_DAY = 0;
const WORK_ALL_DAY = 1;
const WORK_HALF_DAY = 0.5;

// salary day off
const PAID_LEAVE = 1;
const UNPAID_LEAVE = 0;
const UNPAID_LEAVE_HALF = 2;
const LEAVES_HOUR = 0;
const LEAVE_NO_CANCEL_REQUEST = 0;
const LEAVE_PENDING_CANCEL_REQUEST = 1;
const LEAVE_APPROVED_CANCEL_REQUEST = 2;
const STATUS_PENDING_APPROVAL = 0;
const STATUS_APPROVAL = 1;
const STATUS_REJECT = 2;
const SHIFT_ALL_DAY = 0;
const SHIFT_MORNING = 1;
const SHIFT_AFTERNOON = 2;

const CANCEL_REQUEST_NO = 0;
const CANCEL_REQUEST_ARE_REQUESTING = 1;
const CANCEL_REQUEST_CONFIRMED = 2;
const CANCEL_REQUEST_CANCEL = 3;

// time source
const LAST_YEAR_TIME_OFF = 0;
const CURRENT_YEAR_TIME_OFF = 1;
const BOTH_TIME_OFF = 2;

// time day
const TIME_HALF_DAY = 4;
const TIME_ALL_DAY = 8;

// country
const VN = "vi";
const JP = "jp";

const CURRENT_PASSWORD_INCORRECT = "CURRENT_PASSWORD_INCORRECT";
const PASSWORD_NOT_SAME = "PASSWORD_NOT_SAME";
const EMAIL_INCORRECT = "EMAIL_INCORRECT";
const PASSWORD_INCORRECT = "PASSWORD_INCORRECT";
const NO_ADDITIONAL_LEAVE_ALLOWED = 'NO_ADDITIONAL_LEAVE_ALLOWED';
const EXISTED_LEAVE_WAITING_ON_DAY = 'EXISTED_LEAVE_WAITING_ON_DAY';
const CANCEL_REQUEST_NOT_SEND = 'CANCEL_REQUEST_NOT_SEND';
const CREATOR_ONLY_PERMISSION = 'CREATOR_ONLY_PERMISSION';
const LEAVE_REJECTED = 'LEAVE_REJECTED';
const DAY_IS_WEEKEND = 'DAY_IS_WEEKEND';
const ACCOUNT_IS_INACTIVE = 'ACCOUNT_IS_INACTIVE';
const NO_CREATE_LEAVE_ON_DAY_OFF = 'NO_CREATE_LEAVE_ON_DAY_OFF';
const SHIFT_OF_LEAVE_EXISTED_ON_DAY = 'SHIFT_OF_LEAVE_EXISTED_ON_DAY';
const SHIFT_OF_LEAVE_EXISTED_MORNING = 'SHIFT_OF_LEAVE_EXISTED_MORNING';
const SHIFT_OF_LEAVE_EXISTED_AFTERNOON = 'SHIFT_OF_LEAVE_EXISTED_AFTERNOON';

const EXIST_LEAVE_ON_DAY = 'EXIST_LEAVE_ON_DAY';
const EXIST_USER_OF_ROLE = 'EXIST_USER_OF_ROLE';

const EXIST_USER_OF_APPOVER = 'EXIST_USER_OF_APPOVER';
const LEADER_OF_ACTIVE_STAFF = 'LEADER_OF_ACTIVE_STAFF';
const CANNOT_INACTIVATE_YOURSELF = 'CANNOT_INACTIVATE_YOURSELF';
const ONLY_ONE_ACTIVE_ADMIN = 'ONLY_ONE_ACTIVE_ADMIN';
const LEADER_INACTIVE = 'LEADER_INACTIVE';

// leave
const PROBATION_LEAVE_IS_UNPAID = 'PROBATION_LEAVE_IS_UNPAID';
const INTERN_LEAVE_IS_UNPAID = 'INTERN_LEAVE_IS_UNPAID';

// message merge leave
const LEAVE_IS_MERGED = 'LEAVE_IS_MERGED';
